### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by willkg** [mythmon/edwin#13]
Edwin needs a favicon.

**Comment by willkg** [comment]
I asked rehan to look into it if he was so interested.

**Comment by rehandalal** [comment]
![favicon](https://cloud.githubusercontent.com/assets/987136/7375042/e659aeee-eda3-11e4-85f1-db222ea5f27c.png)

**Comment by willkg** [comment]
Landed in f53c6d73619c9820fd3bd41cb92e1fbbaf27d6dd
