### ISSUE TITLE
change bugs search to use team slug

### ISSUE THREAD

**Issue by willkg** [mythmon/edwin#22]
We want edwin to be useable by other projects. To do that, we need to use an identifier that's unique project-to-project.

This code searches for all bugs with `s=2015.7` in the whiteboard:

https://github.com/mythmon/edwin/blob/f53c6d73619c9820fd3bd41cb92e1fbbaf27d6dd/edwin/client/static/js/client.browserify.js#L23

I think the ultimate goal is to have edwin searching for bugs that have a comment 0 tag that starts with "edwin-<TEAM>".

We probably want to change to that.

**Comment by mythmon** [comment]
NB: We aren't actually searching specifically for comment 0 having the matching tag. I don't think Bugzilla will actually let us do that. That doesn't really matter though.

**Comment by mythmon** [comment]
This got done at some point.
