### ISSUE TITLE
application error (2015/5/8)

### ISSUE THREAD

**Issue by willkg** [mythmon/edwin#25]
The edwin app on heroku is getting an application error right now:

```

Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

I can't see more without getting heroku all set up locally.

**Comment by mythmon** [comment]
This happens because we currently have to run collectstatic at runtime. Sometimes that takes too long, so gunicorn doesn't bind to the port in time, and Heroku assumes the app is broken.

**Comment by mythmon** [comment]
I spent today working on setting up Heroku's new Docker-based deployments, which gives us a lot more control over the build process without mucking with buildpacks. That means that collectstatic will actually work, and won't happen at runtime, and so this problem shouldn't show up again
