### ISSUE TITLE
TypeError: Router.run is not a function

### ISSUE THREAD

**Issue by willkg** [mythmon/edwin#26]
When I load edwin locally with master tip (3459c49 Update README about configuration), I get:

```
TypeError: Router.run is not a function   client.browserify.browserified.js:45954:0
```

I went through the README and made sure I had the latest requirements and such. I'm not sure what the issue might be.

**Comment by mythmon** [comment]
Weird. Generally at this point I would start adding `console.log` calls to the code to try and figure out what `Router` and `Router.run` are. Alternatively, you could try and use the debugger to answer the same question, though in this code base with the current Firefox dev tools that is a little hard. (Chrome is slightly better). This is working fine on my laptop and on Heroku.

If you run `npm ls`, do you see `react-router@0.13.3` installed?

**Comment by willkg** [comment]
I did see `react-router@0.13.3`.

On a lark, I wiped my edwin directory, did a "git clone", installed everything and now it works. Yay. No clue what the problem was, though.
