### ISSUE TITLE
Update Dockerfile to match Python template

### ISSUE THREAD

**Issue by mythmon** [mythmon/edwin#29]
When I wrote the Dockerfile, I made up all the Python stuff because I didn't know there was a Python template I could reference. Now I know that [python/Dockerfile.t](https://github.com/heroku/heroku-docker/blob/master/platforms/python/Dockerfile.t) exists.

The Dockerfile we use should be updated to work similarly to the Python template, especially making it use the Python buildpack.

We might run into some errors or false-errors around collectstatic. The reason we are using Docker in the first place is because the python buildpack does strange things that don't play nice with Node during build time.

**Comment by mythmon** [comment]
I figured out how to get the buildpacks to play nice, so we aren't using docker anymore.

**Comment by willkg** [comment]
Hooray! Congratulations!
