### ISSUE TITLE
title should be "edwin - <product>"

### ISSUE THREAD

**Issue by willkg** [mythmon/edwin#51]
If you've got multiple edwin tabs open, then it's impossible to distinguish between them because the title in both cases is "Edwin".

I think we should change it to "Edwin - {product}".

Are there other options?

**Comment by mythmon** [comment]
"Edwin - {product}" sounds good. We could reverse it, so the tab would look like "[edwin favicon] {product} - Edwin". That would help if you have narrow tabs that can't display the full text, and I think the favicon is still recognizable enough. Do you have a preference for either?

**Comment by willkg** [comment]
I don't have a preference--either is fine.

**Comment by willkg** [comment]
Also, this is not a "must have". It's a "nice to have". If it's hard at all, not worth it.
