### ISSUE TITLE
Clear bugs when moving between teams

### ISSUE THREAD

**Issue by mythmon** [mythmon/edwin#61]
When moving from one team (say, `/t/sumo`) to another (say, `/t/input`), the bugs from the other team are kept in the bug list, which is confusing, and more importantly, wrong.

**Comment by willkg** [comment]
Maybe instead of clearing bugs, it should put them in a team namespace? Then if you switch between input and sumo, it doesn't go do all this work.

**Comment by mythmon** [comment]
Ooh, even better. Yes.
